### ISSUE TITLE
add release body

### ISSUE THREAD

**Issue by seiyria** [samuelmeuli/action-electron-builder#37]
is it possible to add a release body? for example, with the `actions/create-release@v1` action you can do this:

```
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          This is an automated release. See [the Changelog](link to my changelog) for more info.
        draft: false
        prerelease: false
```
