### ISSUE TITLE
Can not get the action to work, 

### ISSUE THREAD

**Issue by richard457** [samuelmeuli/action-electron-builder#51]
**I am having the bellow issue:**

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
child_process.js:660
    throw err;
    ^
How Can I fix it?

**Comment by richard457** [comment]
This is my yml file for github action
```
name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest] 
        package_manager: [npm]
        #  macos-latest, ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses:  actions/setup-node@v2.1.2
        with:
          node-version: '10.16.3'

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
```
