### ISSUE TITLE
Build from one repository and release on another one?

### ISSUE THREAD

**Issue by drori200** [samuelmeuli/action-electron-builder#70]
Hey there. I am running into a bit of an issue with a project i am making. i have two repositories which for the purpose of simplifying the explanation i will refer to them as `A` and `B` repository `A` is a private repository that contains the source code for my electron application. repository `B` is the repository where releases for my app will be available. repository `A` pings repository `B` and repository `B` then checks out repo `A` and executes all the different actions i need; only problem is that when the builder gets to the point of releasing the application it tries to release to repository `A`. How would i make it so the app release to repository `B`? Below is my workflow file

```
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
        with:
          repository: HavenCoreNetwork/Launcher
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          args: "-p always"
```
