### ISSUE TITLE
Fail to notarize application

### ISSUE THREAD

**Issue by juli1** [samuelmeuli/action-electron-builder#85]
When running the action, I have the following error

```
Skipping notarizing step. APPLE_ID and APPLE_ID_PASS env variables must be set
```

This is my YML file
```
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
        env:
          # macOS notarization API key
          API_KEY_ID: ${{ secrets.api_key_id }}
          API_KEY_ISSUER_ID: ${{ secrets.api_key_issuer_id }}
```

I also tried to set `APPLE_ID` and `APPLE_ID_PASS` with my appstore credentials but nothing worked.

Any idea why the notarization is skipped/not done?

Thank you,
